name: Test Code Engine GitHub Action

on:
  push:
    branches:
      - main

env:
  CODE_ENGINE_REGION: ${{ vars.IBMCLOUD_REGION }}
  CODE_ENGINE_PROJECT: ${{ vars.CODE_ENGINE_PROJECT }}
  WORKLOAD_NAME: ${{ vars.CODE_ENGINE_APP }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP}}

jobs:

  code-engine-app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Test Appapp deployment to Code Engine
      uses: cloud-design-dev/ibmcloud-code-engine-github-action@v5
      with:
        ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
        resource_group: ${{ env.RESOURCE_GROUP }}
        code_engine_region: ${{ env.CODE_ENGINE_REGION }}
        code_engine_project: ${{ env.CODE_ENGINE_PROJECT }}
        workload_type: 'app'
        workload_name: ${{ env.WORKLOAD_NAME }}
        workload_port: '80'
        build_source: './'
